### ISSUE TITLE
Docs: weight <= 0 seems to be restrictive

### ISSUE THREAD

**Issue by nilsbecker** [laelath/ocaml-urn#1]
in the docs of `U` and `Make`, at several spots an error is documented, if `w <= 0`. Should that not be , ` <= Weights.zero`, strictly speaking? Or even more strictly speaking `Weights.(compare zero w <= 0)`? 

It's a bit hard to refer to that value because the input signature is not exposed in the output, but if some other type of weights apart from integers or floats were used, the docs would not make sense. 

on the other hand, i don't know if there even is another sensible type of weights?

**Comment by laelath** [comment]
Yeah, I wasn't quite sure how to phrase those comments. It is indeed implemented using the given zero and compare functions, though it's good to know the documentation is misleading
